CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    name  VARCHAR                                 NOT NULL,
    email VARCHAR                                 NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS requests
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    description  VARCHAR                                 NOT NULL,
    user_id      BIGINT                                  NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    request_date TIMESTAMP                               NOT NULL
);

CREATE TABLE IF NOT EXISTS items
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    name        VARCHAR                                 NOT NULL,
    description VARCHAR                                 NOT NULL,
    available   BOOLEAN                                 NOT NULL,
    user_id     BIGINT                                  NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    request_id  BIGINT                                  REFERENCES requests (id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS booking
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    start_time TIMESTAMP                               NOT NULL,
    end_time   TIMESTAMP                               NOT NULL,
    item_id    BIGINT                                  NOT NULL REFERENCES items (id) ON DELETE CASCADE,
    user_id    BIGINT                                  NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    status     varchar DEFAULT 'WAITING'               NOT NULL CHECK (status IN ('WAITING', 'APPROVED', 'REJECTED', 'CANCELLED'))
);

CREATE TABLE IF NOT EXISTS comments
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    text    varchar                                 NOT NULL,
    item_id BIGINT                                  NOT NULL REFERENCES items (id) ON DELETE CASCADE,
    user_id BIGINT                                  NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    created timestamp                               NOT NULL
)